<?php use Phalcon\Tag as Tag; ?>
<?php echo $this->getContent() ?>
<?php echo $this->flashSession->output() ?>
<?php if($page): ?>
<?php foreach ($page->items as $model): ?>
<div class="last">
<div class="search">
<div class="search-txt">
<span class="search-txt-h">
<a href="/posts/show/<?php echo $model->id ?>/<?php echo $model->slug ?>" target="_blank"><?php echo
mb_substr(strip_tags($model->title), 0, 230, "UTF-8") ?>
</a></span><br />
<span class="search-txt-desk"><?php echo mb_substr(strip_tags($model->body), 0, 430, "UTF-8") ?>...</span>
</div><!--search-txt-->
<div class="clr-both"></div>
</div><!--search-->
</div><!--last-->
<div class="nav">
		<b>Тэги: </b>
		<?php echo implode(', ', $model->getTagLinks()); ?>
		<br/>
</div>
<hr class="" />
<?php endforeach ?>
<?php else: ?>
<?php echo '<p>Ничего не найдено.</p>'; ?>
<?php endif; ?>