<?php
use Phalcon\Tag as Tag
?>
<div id="main-search-form">
<div class="inline scaffold left">
<?php
echo Tag::form(array(
	"backend/users/index",
	"autocomplete" => "off",
	"class" => "form-inline"))
?>

    <h5>Пользователи</h5>
 
<div class="clearfix"></div>
<?php
echo Tag::textField(array(
	"id",
	"size" => 5,
	"maxlength" => 10,
	"class" => "input-mini left",
	"placeholder" => "ID",
	"type" => "number"))
?>

<?php
echo Tag::textField(array(
	"name",
	"class" => "input-large",
	"size" => 44,
	"maxlength" => 70,
	"placeholder" => "Имя",
	"name" => "name",
	))
?>
  
  <?php
echo Tag::textField(array(
	"email",
	"class" => "input-large",
	"size" => 44,
	"maxlength" => 70,
	"placeholder" => "Почта",
	"name" => "email",
	))
?>
  
  <?php
echo Tag::select(array(
	'profilesId',
	"class" => "input-medium left",
	\Models\Roles::find('active = "Y"'),
	'using' => array('id', 'name'),
	'useEmpty' => true,
	'emptyText' => 'Роль',
	'emptyValue' => ''));
?>

<?php
echo Tag::selectStatic(array(
	"active",
	"name" => "active",
	"class" => "input-small left"), array(
	"Y" => "Активный",
	"N" => "Скрытый",
	'' => ''));
?>
    
<?php
echo Tag::selectStatic(array(
	"banned",
	"name" => "banned",
	"class" => "input-small left"), array(
	"Y" => "Забанен",
	"N" => "Нет",
	'' => ''));
?>
    
<?php
echo Tag::selectStatic(array(
	"suspended",
	"name" => "suspended",
	"class" => "input-small left"), array(
	"Y" => "Приостановлен",
	"N" => "Нет",
	'' => ''));
?>
  
    
<?php
echo Tag::submitButton(array("Поиск", "class" => "btn search"))
?>
</form>
</div>
</div>

