<?php
use Phalcon\Tag as Tag
?>
<?php
$this->getContent()
?>

<form method="post">

<h2>Управление правами доступа ролей</h2>

<div class="well" align="center">

	<table class="perms">
		<tr>
			<td><label for="role_id">Укажите роль</label></td>
			<td>   <?php
echo Tag::select(array(
	'role_id',
	"class" => "input-medium left",
	\Models\Roles::find('active = "Y"'),
	'using' => array('id', 'name'),
	'useEmpty' => true,
	'emptyText' => 'Роль',
	'emptyValue' => ''));
?></td>
			<td> <?php
echo Tag::submitButton(array(
	"Поиск",
	"class" => "btn btn-primary",
	//"onclick" => "return UpdateProduct.validate();",
	))
?></td>
		</tr>
	</table>
</div>
<?php
if ($this->request->isPost() and isset($profile)):
?>

<?php
	foreach ($this->acl->getResources() as $resource => $actions):
?>

	<h3> <?php
		echo $resource
?></h3>

	<table class="table table-bordered table-striped" align="center">
		<thead>
			<tr>
				<th width="5%"></th>
				<th>Описание</th>
			</tr>
		</thead>
		<tbody>
      <?php
		foreach ($actions as $action):
?>
			<tr>
        <td align="center"><input type="checkbox" name="permissions[]" value="<?php echo $resource . '.' . $action ?>"  <?php if (isset($permissions[$resource . '.' . $action])): ?> checked="checked" <?php endif ?>></td>
				<td><?php echo $this->acl->getActionDescription($action) . ' ' . $resource ?></td>
			</tr>
      <?php
		endforeach
?>
		</tbody>
	</table>
<?php
	endforeach
?>
<?php
endif
?>

</form>