<?php use Phalcon\Tag as Tag ?>

<?php echo Tag::form(array(
  "backend/users/edit",
  "id" => "editUserForm",
  "autocomplete" => "off",
  //"enctype" => "multipart/form-data",
  "onbeforesubmit" => "return false")) ?>


<div class="center scaffold">
<?php echo $this->flashSession->output() ?>
    <h2>Редактирование данных о пользователе <?php echo $model->name ?>.</h2>
    
  <input type="hidden" name="id" id="id" value="<?php echo $model->id ?>" />
  
  <div class="clearfix">
        <label for="name"><strong>Имя:</strong></label>
        <?php echo Tag::textField(array(
  "name",
  "class" => "span6 input-xlarge",
  "size" => 44,
  "maxlength" => 70,
  "name" => "name",
  )) ?>
    </div>
    
    <div class="clearfix">
        <label for="email">Почта</label>
        <?php echo Tag::textField(array(
  "email",
  "class" => "span6 input-xlarge",
  "size" => 44,
  "maxlength" => 70,
  "name" => "email",
  )) ?>
    </div>
    
    <div class="clearfix">
        <label for="role_id">Роль</label>
    <?php
echo Tag::select(array(
	'role_id',
	"class" => "input-medium left",
	\Models\Roles::find('active = "Y"'),
	'using' => array('id', 'name'),
	'useEmpty' => true,
	'emptyText' => 'Роль',
	'emptyValue' => ''));
?>
    </div>
    
    <div class="clearfix">
        <label for="active">Подтверждена регистрация?</label>
    <?php
echo Tag::selectStatic(array(
	"active",
	"name" => "active",
	"class" => "input-small left"), array(
	"Y" => "Да",
	"N" => "Нет",
	'' => ''));
?>
    </div>
    
    <div class="clearfix">
        <label for="banned">Забанен?</label>
    <?php
echo Tag::selectStatic(array(
	"banned",
	"name" => "banned",
	"class" => "input-small left"), array(
	"Y" => "Забанен",
	"N" => "Нет",
	'' => ''));
?>
    </div>
    
    <div class="clearfix">
        <label for="suspended">Приостановлен?</label>
    <?php
echo Tag::selectStatic(array(
	"suspended",
	"name" => "suspended",
	"class" => "input-small left"), array(
	"Y" => "Да",
	"N" => "Нет",
	'' => ''));
?>
    </div>
   
   <ul class="pager">
    <li class="pull-right">
        <?php echo Tag::submitButton(array(
  "Сохранить",
  "class" => "btn btn-success",
  //"onclick" => "return UpdateProduct.validate();",
  )) ?>
    </li>
</ul> 
    
</div>
</form>