<?php  use Phalcon\Tag as Tag ?>

<ul class="pager">
    <li class="previous pull-left">
        <?php echo Tag::linkTo("backend/articleCategories/index", "&larr; Назад") ?>
    </li>
    <li class="pull-right">
        <?php echo Tag::linkTo(array(
  "backend/articleCategories/edit/" . $model->id,
  "Редактировать",
  "class" => "btn btn-primary")) ?>
    </li>
</ul>
<div class="center">
<?php echo $this->flashSession->output() ?>
<table class="table table-hover table-bordered">
  <caption><h4><i>Просмотр категории новостей <?php echo $model->name ?></i></h4></caption>
  <tbody>
    <tr>
      <td>Id</td>
      <td><?php echo $model->id; ?></td>
    </tr>
    <tr>
      <td>Название</td>
      <td><?php echo $model->name; ?></td>
    </tr>
  </tbody>
</table>
</div> 